ALTER TABLE Users
    ADD COLUMN Gender VARCHAR(20) NULL,
    ADD COLUMN ActivityLevel VARCHAR(40) NULL,
    ADD COLUMN FitnessGoal VARCHAR(20) NULL,
    ADD COLUMN TargetCalories INT NULL,
    ADD COLUMN TargetProtein DECIMAL(8,2) NULL,
    ADD COLUMN TargetCarbs DECIMAL(8,2) NULL,
    ADD COLUMN TargetFat DECIMAL(8,2) NULL,
    ADD COLUMN Bmi DECIMAL(5,2) NULL,
    ADD COLUMN Bmr INT NULL,
    ADD COLUMN Tdee INT NULL,
    ADD COLUMN MacroTargetsUpdatedAt TIMESTAMP NULL;
